/// Edit listener interface for the editable_document command architecture.
///
/// [EditListener]s are notified after every [Editor.submit] cycle completes,
/// including any additional requests generated by reactions.
library;

import 'document_change_event.dart';

// ---------------------------------------------------------------------------
// EditListener
// ---------------------------------------------------------------------------

/// A sink that receives the complete list of [DocumentChangeEvent]s produced
/// by a single [Editor.submit] cycle.
///
/// Implement this interface to observe document changes after they have been
/// applied. Unlike [EditReaction], a listener cannot inject additional
/// requests — it is purely observational.
///
/// Register listeners with [Editor.addListener] and deregister with
/// [Editor.removeListener].
///
/// Example:
/// ```dart
/// class MyListener implements EditListener {
///   @override
///   void onEdit(List<DocumentChangeEvent> changes) {
///     for (final event in changes) {
///       debugPrint('Document changed: $event');
///     }
///   }
/// }
///
/// editor.addListener(MyListener());
/// ```
abstract interface class EditListener {
  /// Called once per [Editor.submit] cycle after all reactions have run.
  ///
  /// [changes] contains every [DocumentChangeEvent] produced during that
  /// cycle, including events from commands triggered by reactions.
  void onEdit(List<DocumentChangeEvent> changes);
}
